server:
  port: 8082
  servlet:
    path: /sales
logging:
  level:
    com.targetmol:  info

spring:
  application:
    name: sales-service
  datasource:
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 11111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://192.168.3.15:3306/tsbio?&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: root
    password: ts@801

mybatis:
  type-aliases-package: com.targetmol.domain #别名路径
  configuration:
    map-underscore-to-camel-case: true      #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone:  http://192.168.3.13:10086/eureka
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #  服务发现开关
  instance:
    prefer-ip-address: true
    ip-address: localhost #212313
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间