server:
  port: 10086
spring:
  application:
    name: Erp-registry
eureka:
  client:
    service-url:
      defaultZone: http://192.168.3.13:10086/eureka
    fetch-registry: false        #自己本身不在注册中心中进行拉取
    register-with-eureka: false   #自己本身不在注册中心中进行注册
  server:     #test
    enable-self-preservation: false   #关闭自我保护模式
    eviction-interval-timer-in-ms: 60000    #服务注册表清理间隔（单位毫秒，默认就是60*1000）
  instance:
    prefer-ip-address: true
    #ip-address:  ${spring.cloud.client.ip-address}
    ip-address:  ${host}
    #hostname:  ${spring.cloud.client.ip-address}