server:
  port: 8100
  servlet:
    path: /file
logging:
  level:
    com.targetmol:  info


spring:
  application:
    name: files-service
  datasource:
    #driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver 11111
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL:jdbc:mysql://192.168.3.15:3306/tsbio?&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai}
    username: root
    password: ts@801
  data:
    mongodb:
      uri: mongodb://root:123@192.168.3.15:27017
      database: tsbio_fs
  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 10MB
      # 最大支持请求大小
      max-request-size: 50MB
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    service-url:
      defaultZone:  http://192.168.3.13:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 192.168.3.13
ribbon:
  ConnectionTimeout: 5000   #ribbon连接超时时长1000毫秒
  ReadTimeout: 6000  #ribbon读取超时时长 6000毫秒
  MaxAutoRetries: 2   #当前服务重启次数
  MaxAutoRetriesNextServer: 3   #切换服务重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
tsbio:
  fastdfs:
    connect_timeout_in_seconds: 30000
    network_timeout_in_seconds: 60000
    charset: UTF-8
    tracker_servers: 192.168.3.15
    tracker_port: 22122 #多个 trackerServer中间以逗号分隔
    file_port: 8888   #下载文件端口
    expireAt: 30  #网页过期时间（天）
    shortUrl: http://tar.red:66/
