server:
  port: 8100
  servlet:
    path: /file
logging:
  level:
    com.targetmol:  info

spring:
  application:
    name: file-service
    data:
      mongodb:
        database: tsbio_fs
        uri: mongodb://root:123@192.168.3.15:27017


  servlet:
    multipart:
      #默认支持文件上传.
      enabled: true
      #支持文件写入磁盘.
      file-size-threshold: 0
      # 上传文件的临时目录
      location:
      # 最大支持文件大小
      max-file-size: 10MB
      # 最大支持请求大小
      max-request-size: 50MB
mybatis:
  type-aliases-package: com.targetmol.domain #别名路径
  configuration:
    map-underscore-to-camel-case: true      #驼峰命名
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone:  http://192.168.3.13:10086/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
ribbon:
  ConnectionTimeout: 5000   #ribbon连接超时时长1000毫秒
  ReadTimeout: 6000  #ribbon读取超时时长 6000毫秒
  MaxAutoRetries: 2   #当前服务重启次数
  MaxAutoRetriesNextServer: 3   #切换服务重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
tsbio:
  fastdfs:
    connect_timeout_in_seconds: 5
    network_timeout_in_seconds: 30
    charset: UTF-8
    tracker_servers: 192.168.3.15
    tracker_port: 22122 #多个 trackerServer中间以逗号分隔
    file_port: 8888   #下载文件端口