server:
  port: 8080
  servlet:
    path: /
logging:
  level:
    com.targetmol:  info

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://127.0.0.1:1433; DatabaseName=tsbio
    username: tsbio
    password: ts@801
mybatis:
  type-aliases-package: com.targetmol.domain #别名路径
  configuration:
    map-underscore-to-camel-case: true      #驼峰命名
